name: Test

on: [pull_request, push]

jobs:
  test:
    name: Check that the tests are passing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installation
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

